server:
  port: 8083

spring:
  application:
    name: ai-service
  data:
    mongodb:
      uri: mongodb://host.docker.internal:27017/fitnessrecommendation
      database: fitnessrecommendation
      auto-index-creation: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  metrics:
    tags:
      application: ${spring.application.name}
