
services:
  eureka:
    build: ./eureka
    ports:
      - "8761:8761"
    networks:
      - fitness-net
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:8761 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  configserver:
    build: ./configserver
    ports:
      - "8888:9999"
    depends_on:
      eureka:
        condition: service_healthy
    networks:
      - fitness-net
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:9999/application/default || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - fitness-net

  userservice:
    build: ./userservice
    ports:
      - "8081:8081"
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      - fitness-net

  activityservice:
    build: ./activityservice
    ports:
      - "8082:8082"
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - fitness-net

  aiservice:
    build: ./aiservice
    ports:
      - "8083:8083"
    depends_on:
      eureka:
        condition: service_healthy
      configserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      - GEMINI_API_URL=${GEMINI_API_URL}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - fitness-net

  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - fitness-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  fitness-net:
    driver: bridge
